import type {LiveEvent} from '../types';

export function ModelInsights({event}:{event:LiveEvent|null}){
  if(!event)return <section className="clean-card stream-empty"><i/><h3>No scored event selected</h3><p>Run a simulation or select a row in Live Activity to inspect actual model output.</p></section>;
  const evidence=event.feature_evidence?.length?event.feature_evidence:Object.entries(event.features||{}).map(([feature,value])=>({feature,value,baseline:0,deviation:0,description:''}));
  return <div className="insights-layout"><section className="clean-card insight-summary"><div className="section-heading"><h2>Selected model verdict</h2><span>{event.event_id}</span></div><div className="insight-kpis"><div><span>Predicted attack</span><strong>{event.display_attack||event.predicted_attack.replaceAll('_',' ')}</strong></div><div><span>Classifier confidence</span><strong>{(event.classifier_confidence*100).toFixed(1)}%</strong></div><div><span>Isolation Forest score</span><strong>{event.anomaly_score.toFixed(3)}</strong></div><div><span>GRU sequence score</span><strong>{(event.sequence_anomaly_score||0).toFixed(3)}</strong></div><div><span>Final risk</span><strong>{event.risk_score.toFixed(1)}</strong></div></div><p>{event.explanation}</p><div className="version-row"><span>Entity <b>{event.entity_id}</b> · {event.entity_type?.replaceAll('_',' ')}</span><span>Baseline <b>{event.baseline_type}</b>{event.cold_start?' · cold start':''}</span><span>Incident events <b>{event.incident_event_count||1}</b></span><span>Model <b>{event.model_version}</b></span><span>Feature schema <b>{event.feature_schema_version}</b></span></div></section>
    <section className="clean-card feature-insights"><div className="section-heading"><h2>{evidence.length}-feature evidence</h2><span>Actual extracted values</span></div><div className="feature-table"><div className="feature-row feature-header"><b>Feature</b><span>Value</span><span>Baseline</span><span>Deviation</span></div>{evidence.map(item=><div className="feature-row" key={item.feature}><div><b>{item.feature.replaceAll('_',' ')}</b><small>{item.description}</small></div><span>{Number(item.value).toFixed(3)}</span><span>{Number(item.baseline||0).toFixed(3)}</span><span>{Number(item.deviation||0).toFixed(3)}</span></div>)}</div></section>
    <section className="clean-card probability-card"><div className="section-heading"><h2>Attack-class probabilities</h2><span>Classifier output</span></div><div className="probability-list">{Object.entries(event.class_probabilities||{}).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><label><b>{name.replaceAll('_',' ')}</b><span>{(value*100).toFixed(1)}%</span></label><div><i style={{width:`${value*100}%`}}/></div></div>)}</div></section>
    <section className="clean-card risk-calculation"><div className="section-heading"><h2>Final risk calculation</h2><span>Weighted evidence</span></div><div className="risk-components">{Object.entries(event.risk_composition||{}).map(([name,value])=><div key={name}><span>{name.replaceAll('_',' ')}</span><strong>+{value.toFixed(2)}</strong></div>)}<div className="total"><span>Final risk</span><strong>{event.risk_score.toFixed(2)} / 100</strong></div></div><h3>Top contributing features</h3>{(event.top_contributing_features||[]).map(item=><div className="contribution" key={item.feature}><div><b>{item.feature.replaceAll('_',' ')}</b><span>{item.description}</span></div><strong>{item.deviation.toFixed(2)}</strong></div>)}</section></div>;
}
