import {ArrowUpRight,CalendarRange,ShieldAlert,TrendingUp,UsersRound} from 'lucide-react';
import type {BehaviorRankings} from '../types';

const score=(value:number)=>Math.round(value*10)/10;

export function BehaviorPage({behavior,onViewProfile}:{behavior:BehaviorRankings;onViewProfile:(id:string)=>void}){
  const rows=behavior.rankings||[],leader=rows[0];
  return <><header className="page-head"><div><span className="eyebrow">LONG-TERM BEHAVIOR</span><h1>Identity risk</h1><p>Thirty-day next-day forecasting ranks sustained behavioral drift without turning anomaly scores into attack probabilities.</p></div><span className={`drift-state ${behavior.model_ready?'stable':'learning'}`}><i/>{behavior.model_ready?'forecasting active':'retraining required'}</span></header>
    <section className="behavior-kpis"><article><UsersRound/><div><span>Ranked identities</span><strong>{rows.length}</strong><small>{behavior.daily_observations||0} finalized entity-days</small></div></article><article><TrendingUp/><div><span>Highest concern</span><strong>{leader?score(leader.rank_score):0}</strong><small>{leader?.entity_id||'Waiting for history'}</small></div></article><article><ShieldAlert/><div><span>Maximum drift</span><strong>{leader?`${(leader.maximum_drift_30d*100).toFixed(0)}%`:'0%'}</strong><small>Dominant ranking factor</small></div></article><article><CalendarRange/><div><span>Forecast contract</span><strong>{behavior.window_days} days</strong><small>Minimum {behavior.minimum_history_days||7} observed days</small></div></article></section>
    <section className="panel behavior-ranking"><header><div><span className="eyebrow">PRIORITY ORDER</span><h2>Behavioral concern ranking</h2></div><small>Max drift receives 60% of rank weight</small></header>{!behavior.model_ready?<div className="behavior-empty"><TrendingUp/><h3>Train the behavioral-drift artifact</h3><p>The active artifact predates the 42-feature EntityBehaviorGRU. Run the training command to activate this page.</p></div>:!rows.length?<div className="behavior-empty"><CalendarRange/><h3>No daily history yet</h3><p>Ingest multi-day telemetry or run the concept-drift simulation to build entity-day windows.</p></div>:<div className="behavior-table"><div className="behavior-row behavior-head"><span>Rank / identity</span><span>Risk score</span><span>Max drift</span><span>Drift days</span><span>Consecutive</span><span>Latest</span><span/></div>{rows.map(row=><button className="behavior-row" key={row.entity_id} onClick={()=>onViewProfile(row.entity_id)}><span><b>#{row.rank}</b><strong>{row.entity_id}</strong></span><span><i className="rank-bar"><em style={{width:`${Math.min(100,row.rank_score)}%`}}/></i><b>{score(row.rank_score)}</b></span><span>{(row.maximum_drift_30d*100).toFixed(1)}%</span><span>{row.drift_days_30d}</span><span>{row.consecutive_drift_days}</span><span>{(row.latest_score*100).toFixed(1)}%</span><span><ArrowUpRight/></span></button>)}</div>}</section>
  </>;
}
