import {GitCompareArrows} from 'lucide-react';
import type {DriftResponse} from '../types';

export function DriftPage({drift}:{drift:DriftResponse}){
  const events=drift.events||[],windows=drift.windows||[];
  return <><header className="page-head"><div><span className="eyebrow">BEHAVIOR CHANGE</span><h1>Concept drift</h1><p>Trusted reference and current windows are compared; suspicious events never update them automatically.</p></div></header>
    {windows.length>0&&<section className="drift-windows">{windows.map(window=><article className="panel" key={window.entity}><div><span className="eyebrow">{window.status.replaceAll('_',' ')}</span><h2>{window.entity}</h2><small>Trusted events only</small></div><div className="window-progress"><label><span>Reference window</span><b>{window.reference_window.count}/{window.reference_window.target}</b></label><div><i style={{width:`${window.reference_window.count/window.reference_window.target*100}%`}}/></div><label><span>Current window</span><b>{window.current_window.count}/{window.current_window.target}</b></label><div><i style={{width:`${window.current_window.count/window.current_window.target*100}%`}}/></div></div></article>)}</section>}
    <section className="panel drift-list">{events.map(driftEvent=><article key={driftEvent.id}><GitCompareArrows/><div><div className="drift-title"><b>{driftEvent.feature.replaceAll('_',' ')}</b><span className="status investigating">{driftEvent.review_status}</span></div><span>{driftEvent.subject_id} · {new Date(driftEvent.detected_at).toLocaleString()}</span><div className="distribution-row"><div><small>Previous distribution</small><strong>μ {Number(driftEvent.previous_distribution.mean||0).toFixed(2)} · σ {Number(driftEvent.previous_distribution.std||0).toFixed(2)}</strong></div><span>→</span><div><small>Current distribution</small><strong>μ {Number(driftEvent.current_distribution.mean||0).toFixed(2)} · σ {Number(driftEvent.current_distribution.std||0).toFixed(2)}</strong></div><div><small>Drift confidence</small><strong>{(driftEvent.drift_confidence*100).toFixed(1)}%</strong></div></div><p>{driftEvent.recommendation}. Candidate retraining requires analyst review and is never activated automatically.</p></div><strong>{driftEvent.magnitude.toFixed(1)}σ</strong></article>)}{!events.length&&<div className="empty">No significant drift detected. Run the concept-drift simulation to fill the trusted reference and current windows.</div>}</section></>;
}
