import {ArrowLeft,CheckCircle2,MapPin,Shield,TriangleAlert} from 'lucide-react';
import {Bar,BarChart,ResponsiveContainer,XAxis,YAxis} from 'recharts';
import type {AlertDetail} from '../types';import {RiskPill} from '../components/RiskPill';

export function Investigation({detail,onBack,onUpdate}:{detail:AlertDetail|null;onBack:()=>void;onUpdate:(s:string)=>void}){
  if(!detail)return <div className="loading">Loading investigation…</div>;
  const probs=Object.entries(detail.class_probabilities).map(([name,value])=>({name:name.replaceAll('_',' '),value:Math.round(value*100)}));
  const event=detail.event as any,previous=(detail.timeline[1]||{}) as any;
  return <><button className="back" onClick={onBack}><ArrowLeft/> Back to alerts</button><header className="invest-head"><div><span className="eyebrow">ALERT #{detail.id}</span><h1>{detail.predicted_attack.replaceAll('_',' ')}</h1><p>{detail.user_id} · {detail.device_id} · {new Date(detail.timestamp).toLocaleString()}</p></div><RiskPill score={detail.risk_score} severity={detail.severity}/></header>
    <section className="invest-grid"><div><article className="panel rationale"><div className="panel-title"><div><span>MODEL EXPLANATION</span><h2>Why this was flagged</h2></div><TriangleAlert/></div><p>{detail.explanation_detail.text}</p>{detail.explanation_detail.top_contributing_features.map(f=><div className="contribution" key={f.feature}><div><b>{f.feature.replaceAll('_',' ')}</b><span>{f.description}</span></div><strong>{f.value.toFixed(2)}</strong></div>)}</article>
      <article className="panel"><div className="panel-title"><div><span>CLASSIFIER</span><h2>Attack probabilities</h2></div></div><ResponsiveContainer width="100%" height={220}><BarChart data={probs} layout="vertical"><XAxis type="number" domain={[0,100]} hide/><YAxis dataKey="name" type="category" width={120} tick={{fill:'var(--muted)',fontSize:9}} axisLine={false} tickLine={false}/><Bar dataKey="value" fill="var(--accent)" radius={0}/></BarChart></ResponsiveContainer></article>
      <article className="panel evidence"><div className="panel-title"><div><span>EVENT EVIDENCE</span><h2>Device and location</h2></div><MapPin/></div><dl><div><dt>Current location</dt><dd>{event.city}, {event.country}</dd></div><div><dt>Previous location</dt><dd>{previous.city?`${previous.city}, ${previous.country}`:'No earlier event'}</dd></div><div><dt>Source IP</dt><dd>{event.source_ip}</dd></div><div><dt>Device</dt><dd>{event.operating_system} · {event.browser}</dd></div><div><dt>Destination</dt><dd>{event.destination_host}</dd></div></dl><div className="mini-timeline">{detail.timeline.slice(0,5).map((row:any,i)=><div key={i}><i/><span>{new Date(row.timestamp).toLocaleString()}</span><b>{row.event_type?.replaceAll('_',' ')}</b><em>{row.city}</em></div>)}</div></article></div>
      <aside><article className="panel action"><div className="panel-title"><div><span>ANALYST ACTION</span><h2>Disposition</h2></div><Shield/></div><button onClick={()=>onUpdate('investigating')}>Start investigation</button><button className="danger" onClick={()=>onUpdate('confirmed_threat')}>Confirm threat</button><button className="safe" onClick={()=>onUpdate('false_positive')}><CheckCircle2/> Mark false positive</button></article><article className="panel context"><div className="panel-title"><div><span>CONTEXT</span><h2>Behavior baseline</h2></div><MapPin/></div><dl><div><dt>Baseline</dt><dd>{detail.baseline_type}</dd></div><div><dt>Confidence</dt><dd>{Math.round(detail.baseline_confidence*100)}%</dd></div><div><dt>Anomaly score</dt><dd>{detail.anomaly_score.toFixed(3)}</dd></div><div><dt>Model</dt><dd>{detail.model_version}</dd></div></dl></article></aside></section></>;
}
