import {ArrowLeft,CheckCircle2,MapPin,Shield,TriangleAlert,UserRound} from 'lucide-react';
import {Bar,BarChart,ResponsiveContainer,XAxis,YAxis} from 'recharts';
import type {AlertDetail} from '../types';
import {RiskPill,RISK_TOOLTIP} from '../components/RiskPill';

const statuses=['open','investigating','confirmed_threat','false_positive','closed'];
export function Investigation({detail,onBack,onUpdate,onViewProfile}:{detail:AlertDetail|null;onBack:()=>void;onUpdate:(status:string)=>void;onViewProfile:(user:string)=>void}){
  if(!detail)return <div className="loading">Loading investigation…</div>;
  const probabilities=Object.entries(detail.class_probabilities).map(([name,value])=>({name:name.replaceAll('_',' '),value:Math.round(value*100)}));
  const event=detail.event,previous=detail.timeline.find(item=>item.event.event_id!==event.event_id)?.event;
  return <><button className="back" onClick={onBack}><ArrowLeft/> Back to detections</button><header className="invest-head"><div><span className="eyebrow">ALERT #{detail.id} · {detail.status.replaceAll('_',' ')}</span><h1>{detail.display_attack||detail.predicted_attack.replaceAll('_',' ')}</h1><p>{detail.user_id} · {detail.device_id} · {new Date(detail.timestamp).toLocaleString()}</p></div><div className="verdict-stack" title={RISK_TOOLTIP}><RiskPill score={detail.risk_score} severity={detail.severity}/><span>Anomaly {detail.anomaly_score.toFixed(3)}</span><span>Class confidence {(detail.classifier_confidence*100).toFixed(1)}%</span></div></header>
    <section className="invest-grid"><div><article className="panel rationale"><div className="panel-title"><div><span>MODEL EXPLANATION</span><h2>Why this was flagged</h2></div><TriangleAlert/></div><p>{detail.explanation_detail.text}</p>{detail.explanation_detail.top_contributing_features.map(feature=><div className="contribution" key={feature.feature}><div><b>{feature.feature.replaceAll('_',' ')}</b><span>{feature.description} · observed {feature.value.toFixed(2)} · expected {feature.expected?.toFixed?.(2)||'0.00'}</span></div><strong>{feature.deviation.toFixed(2)}</strong></div>)}</article>
      <article className="panel feature-evidence"><div className="panel-title"><div><span>ENGINEERED EVIDENCE</span><h2>All 12 features</h2></div></div><div className="feature-table"><div className="feature-row feature-header"><b>Feature</b><span>Value</span><span>Baseline</span><span>Deviation</span></div>{(detail.feature_evidence||[]).map(feature=><div className="feature-row" key={feature.feature}><div><b>{feature.feature.replaceAll('_',' ')}</b><small>{feature.description}</small></div><span>{feature.value.toFixed(3)}</span><span>{feature.baseline.toFixed(3)}</span><span>{feature.deviation.toFixed(3)}</span></div>)}</div></article>
      <article className="panel"><div className="panel-title"><div><span>CLASSIFIER</span><h2>Attack-class probabilities</h2></div><b>{(detail.classifier_confidence*100).toFixed(1)}% confidence</b></div><ResponsiveContainer width="100%" height={240}><BarChart data={probabilities} layout="vertical"><XAxis type="number" domain={[0,100]} tick={{fontSize:12,fill:'var(--muted)'}}/><YAxis dataKey="name" type="category" width={150} tick={{fill:'var(--muted)',fontSize:12}} axisLine={false} tickLine={false}/><Bar dataKey="value" fill="var(--purple)" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></article>
      <article className="panel evidence"><div className="panel-title"><div><span>EVENT EVIDENCE</span><h2>Device, fingerprint, and location</h2></div><MapPin/></div><dl><div><dt>Current location</dt><dd>{event.city}, {event.country}</dd></div><div><dt>Previous location</dt><dd>{previous?.city?`${previous.city}, ${previous.country}`:'No earlier event'}</dd></div><div><dt>Source IP</dt><dd>{event.source_ip}</dd></div><div><dt>Device / claimed</dt><dd>{event.device_id} / {event.claimed_device_id}</dd></div><div><dt>Fingerprint</dt><dd>{event.device_fingerprint}</dd></div><div><dt>OS / browser</dt><dd>{event.operating_system} · {event.browser}</dd></div></dl></article>
      <article className="panel"><div className="panel-title"><div><span>ATTACK SEQUENCE</span><h2>Identity timeline</h2></div></div><div className="mini-timeline">{detail.timeline.slice(0,12).map((row,index)=><div key={index}><i className={(row.prediction?.risk_score||0)>=50?'hot':''}/><span>{new Date(row.event.timestamp).toLocaleString()}</span><b>{row.event.event_type?.replaceAll('_',' ')}</b><em>{row.prediction?.predicted_attack?.replaceAll('_',' ')||'unscored'}</em><strong>{row.prediction?.risk_score?.toFixed(1)||'—'}</strong></div>)}</div></article>
      <article className="panel raw-event"><div className="panel-title"><div><span>RAW TELEMETRY</span><h2>Validated event</h2></div></div><pre>{JSON.stringify(event,null,2)}</pre></article></div>
      <aside><article className="panel action"><div className="panel-title"><div><span>ANALYST ACTION</span><h2>Disposition</h2></div><Shield/></div>{statuses.map(status=><button className={status==='confirmed_threat'?'danger':status==='false_positive'?'safe':''} disabled={detail.status===status} onClick={()=>onUpdate(status)} key={status}>{status==='false_positive'&&<CheckCircle2/>}{status.replaceAll('_',' ')}</button>)}</article>
        <article className="panel action"><div className="panel-title"><div><span>IDENTITY</span><h2>Behavior profile</h2></div><UserRound/></div><button onClick={()=>onViewProfile(detail.user_id)}>Open {detail.user_id}</button></article>
        <article className="panel context"><div className="panel-title"><div><span>MODEL CONTEXT</span><h2>Scoring contract</h2></div><MapPin/></div><dl><div><dt>Baseline</dt><dd>{detail.baseline_type}</dd></div><div><dt>Cold start</dt><dd>{detail.cold_start?'Yes · peer/global':'No · user baseline'}</dd></div><div><dt>Baseline confidence</dt><dd>{Math.round(detail.baseline_confidence*100)}%</dd></div><div><dt>Anomaly score</dt><dd>{detail.anomaly_score.toFixed(3)}</dd></div><div><dt>Classifier confidence</dt><dd>{(detail.classifier_confidence*100).toFixed(1)}%</dd></div><div><dt>Model</dt><dd>{detail.model_version}</dd></div><div><dt>Feature schema</dt><dd>{detail.feature_schema_version}</dd></div></dl></article>
        <article className="panel risk-breakdown"><div className="panel-title"><div><span>RISK COMPOSITION</span><h2>{detail.risk_score.toFixed(1)} / 100</h2></div></div>{Object.entries(detail.risk_composition||{}).map(([name,value])=><div key={name}><span>{name.replaceAll('_',' ')}</span><strong>+{value.toFixed(2)}</strong></div>)}</article>
        <article className="panel recommendations"><div className="panel-title"><div><span>RECOMMENDED ACTION</span><h2>Analyst guidance</h2></div></div><ol>{(detail.recommended_actions||[]).map(action=><li key={action}>{action}</li>)}</ol></article>
        <article className="panel feedback-history"><div className="panel-title"><div><span>AUDIT HISTORY</span><h2>Analyst status history</h2></div></div>{detail.feedback.map((feedback,index)=><div key={index}><i/><span><b>{feedback.status.replaceAll('_',' ')}</b><small>{feedback.analyst} · {new Date(feedback.created_at).toLocaleString()}</small><p>{feedback.comment}</p></span></div>)}{!detail.feedback.length&&<p>No analyst feedback recorded yet.</p>}</article></aside></section></>;
}
