import {Eye,EyeOff,LockKeyhole,ShieldCheck} from 'lucide-react';
import {FormEvent,useState} from 'react';
import {api,type AuthUser} from '../services/api';

export function Login({onAuthenticated}:{onAuthenticated:(user:AuthUser)=>void}){
  const[username,setUsername]=useState('admin'),[password,setPassword]=useState('admin'),[visible,setVisible]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError('');try{onAuthenticated(await api.login(username,password))}catch(reason){setError(reason instanceof Error?reason.message:'Unable to sign in')}finally{setLoading(false)}};
  return <main className="login-screen"><section className="login-visual"><div className="login-brand"><span className="brand-symbol"><i/><i/><i/></span><strong>deviance</strong></div><div className="visual-copy"><span>BEHAVIORAL DEFENSE PLATFORM</span><h1>Know what normal looks like.<br/><em>Catch what isn't.</em></h1><p>Machine-learning detection for identity, device, location, and access behavior—built for analysts who need evidence, not noise.</p></div><div className="behavior-orbit"><div className="orbit orbit-one"><i/></div><div className="orbit orbit-two"><i/></div><div className="orbit-core"><ShieldCheck/><span>12</span><small>live signals</small></div><b className="orbit-label one">Identity</b><b className="orbit-label two">Device</b><b className="orbit-label three">Location</b></div><div className="login-foot"><span><i/> Detection engine online</span><b>ML-FIRST · EXPLAINABLE · LIVE</b></div></section>
    <section className="login-panel"><div className="login-form-wrap"><div className="login-icon"><LockKeyhole/></div><span className="login-kicker">SECURE ANALYST ACCESS</span><h2>Welcome back</h2><p>Sign in to open the Deviance investigation workspace.</p><div className="demo-credentials"><div><ShieldCheck/></div><span><b>Hackathon demo credentials</b><small>Username: <code>admin</code> &nbsp; Password: <code>admin</code></small></span></div><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} /></label><label>Password<div className="password-field"><input type={visible?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setVisible(!visible)} aria-label="Show password">{visible?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading}>{loading?'Authenticating…':'Sign in as administrator'}<span>→</span></button></form><small className="login-note">Demo-only access. Change the default credentials and signing secret before any shared deployment.</small></div></section>
  </main>;
}
