import {CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';

export function ModelPage({model}:{model:any}){
  const test=model?.metrics?.test,classes=test?.classes||[],matrix=test?.confusion_matrix||[],selection=model?.metrics?.threshold_selection,curve=selection?.curve||[];
  return <><header className="page-head"><div><span className="eyebrow">MODEL GOVERNANCE</span><h1>Performance</h1><p>Time-aware holdout evaluation and active artifact metadata.</p></div></header>
    <section className="stats model-stats">{[['Macro F1',test?.macro_f1,'Unweighted mean F1 across all attack and normal classes.'],['Weighted F1',test?.weighted_f1,'F1 weighted by chronological holdout class support.'],['Holdout false-positive rate',test?.false_positive_rate,'Normal holdout events classified as an attack by the classifier.'],['Anomaly PR-AUC',test?.anomaly_pr_auc,'Precision-recall area for Isolation Forest attack separation.']].map(([name,value,help])=><article className="metric" key={String(name)} title={String(help)}><span>{name}</span><strong>{typeof value==='number'?(value*100).toFixed(1)+'%':'—'}</strong><small>{help}</small></article>)}</section>
    <section className="panel model-card"><h2>Active artifact</h2><dl><div><dt>Model version</dt><dd>{model?.model_version||'Not trained'}</dd></div><div><dt>Feature schema</dt><dd>{model?.feature_schema_version||'—'}</dd></div><div><dt>Alert threshold</dt><dd>{model?.alert_threshold?.toFixed(1)||'—'}</dd></div><div><dt>Primary features</dt><dd>{model?.feature_names?.length||0}</dd></div><div><dt>Threshold method</dt><dd>{selection?.selection_method||'—'}</dd></div><div><dt>Validation precision / recall</dt><dd>{selection?`${(selection.validation_precision*100).toFixed(1)}% / ${(selection.validation_recall*100).toFixed(1)}%`:'—'}</dd></div></dl>{test?.classification_report&&<div className="class-report"><div className="class-report-head"><b>Class</b><span>Precision</span><span>Recall</span><span>F1</span></div>{Object.entries(test.classification_report).filter(([,value])=>typeof value==='object').map(([name,value]:any)=><div key={name}><b>{name.replaceAll('_',' ')}</b><span>Precision {(value.precision*100).toFixed(0)}%</span><span>Recall {(value.recall*100).toFixed(0)}%</span><span>F1 {(value['f1-score']*100).toFixed(0)}%</span></div>)}</div>}</section>
    {curve.length>0&&<section className="panel threshold-card"><div className="panel-title"><div><span>VALIDATION TUNING</span><h2>Alert-threshold comparison</h2></div><strong>{selection.selected_threshold} selected</strong></div><ResponsiveContainer width="100%" height={260}><LineChart data={curve.map((point:any)=>({...point,precision:point.precision*100,recall:point.recall*100,false_positive_rate:point.false_positive_rate*100}))}><CartesianGrid stroke="var(--grid)" strokeDasharray="4 4"/><XAxis dataKey="threshold" tick={{fontSize:12,fill:'var(--muted)'}}/><YAxis tick={{fontSize:12,fill:'var(--muted)'}}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:10,fontSize:13}}/><Legend/><Line dataKey="precision" stroke="var(--purple)" strokeWidth={2}/><Line dataKey="recall" stroke="var(--pink)" strokeWidth={2}/><Line dataKey="false_positive_rate" stroke="var(--yellow)" strokeWidth={2}/></LineChart></ResponsiveContainer></section>}
    {matrix.length>0&&<section className="panel confusion"><div className="panel-title"><div><span>HOLDOUT VERDICTS</span><h2>Confusion matrix</h2></div></div><div className="matrix"><div/><>{classes.map((className:string)=><b key={className}>{className.replaceAll('_',' ')}</b>)}</>{matrix.map((row:number[],index:number)=><div className="matrix-row" key={classes[index]}><strong>{classes[index].replaceAll('_',' ')}</strong>{row.map((value,column)=><span className={index===column?'correct':''} key={column}>{value}</span>)}</div>)}</div></section>}
  </>;
}
