export function ModelPage({model}:{model:any}){
  const test=model?.metrics?.test,classes=test?.classes||[],matrix=test?.confusion_matrix||[];
  const selection=model?.metrics?.threshold_selection,population=model?.metrics?.training_population||{};
  const cards=[
    ['Macro F1',test?.macro_f1,'Unweighted classification performance across normal, known attacks, and abstentions.'],
    ['Anomaly PR-AUC',test?.anomaly_pr_auc,'Isolation Forest precision-recall area on the imbalanced chronological holdout.'],
    ['Sequence PR-AUC',test?.sequence_pr_auc,'GRU sequence detector precision-recall area on the same holdout.'],
    ['Alert precision',test?.alert_precision,'Precision after applying the operational alert threshold.'],
    ['Alert recall',test?.alert_recall,'Share of attacks surfaced within the calibrated alert budget.'],
    ['Top 1% precision',test?.top_1_percent?.precision,'Attack precision among the highest-risk one percent of holdout events.'],
  ];
  return <><header className="page-head"><div><span className="eyebrow">MODEL GOVERNANCE</span><h1>Performance</h1><p>Entity-safe chronological evaluation under realistic class imbalance and a fixed analyst budget.</p></div></header>
    <section className="stats model-stats">{cards.map(([name,value,help])=><article className="metric" key={String(name)} title={String(help)}><span>{name}</span><strong>{typeof value==='number'?(value*100).toFixed(1)+'%':'—'}</strong><small>{help}</small></article>)}</section>
    <section className="panel model-card"><h2>Active artifact</h2><dl><div><dt>Model version</dt><dd>{model?.model_version||'Not trained'}</dd></div><div><dt>Feature schema</dt><dd>{model?.feature_schema_version||'—'}</dd></div><div><dt>Primary features</dt><dd>{model?.feature_names?.length||0}</dd></div><div><dt>Anomaly model</dt><dd>{model?.anomaly_model?.type||'Isolation Forest'}</dd></div><div><dt>Sequence model</dt><dd>{model?.sequence_model?.type||'GRU sequence detector'} · {model?.sequence_model?.window_size||10} events</dd></div><div><dt>Training policy</dt><dd>IF, scaler, and GRU: normal only · classifier: labeled classes</dd></div></dl>
      {test?.classification_report&&<div className="class-report"><div className="class-report-head"><b>Class</b><span>Precision</span><span>Recall</span><span>F1 / support</span></div>{Object.entries(test.classification_report).filter(([name,value])=>typeof value==='object'&&!['macro avg','weighted avg'].includes(name)).map(([name,value]:any)=><div key={name}><b>{name.replaceAll('_',' ')}</b><span>{(value.precision*100).toFixed(0)}%</span><span>{(value.recall*100).toFixed(0)}%</span><span>{(value['f1-score']*100).toFixed(0)}% · {value.support}</span></div>)}</div>}
    </section>
    <section className="panel threshold-card"><div className="panel-title"><div><span>OPERATIONAL CALIBRATION</span><h2>Analyst alert budget</h2></div><strong>{model?.alert_threshold?.toFixed?.(1)||'—'} risk threshold</strong></div><dl className="budget-grid"><div><dt>Selection method</dt><dd>{selection?.selection_method||'Top 1% validation budget'}</dd></div><div><dt>Validation alert rate</dt><dd>{typeof selection?.validation_alert_rate==='number'?(selection.validation_alert_rate*100).toFixed(2)+'%':'—'}</dd></div><div><dt>Holdout alert rate</dt><dd>{typeof test?.alert_rate==='number'?(test.alert_rate*100).toFixed(2)+'%':'—'}</dd></div><div><dt>Alerts / 10,000 events</dt><dd>{test?.alerts_per_10000?.toFixed?.(1)||'—'}</dd></div><div><dt>Holdout attack prevalence</dt><dd>{typeof test?.attack_prevalence==='number'?(test.attack_prevalence*100).toFixed(2)+'%':'—'}</dd></div><div><dt>Top 1% recall</dt><dd>{typeof test?.top_1_percent?.recall==='number'?(test.top_1_percent.recall*100).toFixed(1)+'%':'—'}</dd></div></dl></section>
    <section className="panel model-card"><h2>Leakage controls</h2><dl><div><dt>Training rows</dt><dd>{population.total_rows??'—'} total · {population.normal_rows??'—'} normal · {population.attack_rows??'—'} attacks</dd></div><div><dt>Preprocessor fit</dt><dd>{population.preprocessor_fit?.replaceAll('_',' ')||'normal only'}</dd></div><div><dt>Isolation Forest fit</dt><dd>{population.anomaly_detector_fit?.replaceAll('_',' ')||'normal only'}</dd></div><div><dt>GRU fit</dt><dd>{population.sequence_detector_fit?.replaceAll('_',' ')||'normal sequences only'}</dd></div><div><dt>Classifier fit</dt><dd>{population.classifier_fit?.replaceAll('_',' ')||'normal and attacks'}</dd></div><div><dt>Probability calibration</dt><dd>{population.classifier_probability_calibration?.replaceAll('_',' ')||'validation sigmoid'}</dd></div></dl></section>
    {matrix.length>0&&<section className="panel confusion"><div className="panel-title"><div><span>HOLDOUT VERDICTS</span><h2>Confusion matrix</h2></div></div><div className="matrix" style={{gridTemplateColumns:`150px repeat(${classes.length}, minmax(85px,1fr))`,minWidth:`${150+classes.length*85}px`}}><div/>{classes.map((className:string)=><b key={className}>{className.replaceAll('_',' ')}</b>)}{matrix.map((row:number[],index:number)=><div className="matrix-row" key={classes[index]}><strong>{classes[index].replaceAll('_',' ')}</strong>{row.map((value,column)=><span className={index===column?'correct':''} key={column}>{value}</span>)}</div>)}</div></section>}
  </>;
}
