import {useState} from 'react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ChevronDown,Play} from 'lucide-react';
import type {LiveEvent,Metrics} from '../types';
import type {StreamState} from '../hooks/useLive';
import {LiveActivity} from '../components/LiveActivity';
import {ModelInsights} from '../components/ModelInsights';
import {SimulationModal} from '../components/SimulationModal';

const palette=['#d8387e','#f6bd19','#42bfd3','#7656c9','#58b982','#ef7c45'];
type Tab='general'|'live'|'insights';

export function Overview({metrics,model,liveEvents,connection}:{metrics:Metrics|null;model:any;liveEvents:LiveEvent[];connection:StreamState}){
  const[tab,setTab]=useState<Tab>('general'),[simulation,setSimulation]=useState(false),[selected,setSelected]=useState<LiveEvent|null>(null);
  if(!metrics)return <div className="loading">Loading behavioral telemetry…</div>;
  const fp=Math.round(metrics.analyst_false_positive_rate_24h*100),maxAttack=Math.max(...Object.values(metrics.attacks_by_type),1);
  const recentRisk=metrics.risk_trend.slice(-20),riskLoad=Math.round(recentRisk.reduce((sum,item)=>sum+item.risk,0)/Math.max(recentRisk.length,1));
  const riskMix=`conic-gradient(#d8387e 0 ${Math.max(metrics.critical_alerts/Math.max(metrics.total_alerts,1)*100,8)}%, #f6bd19 0 42%, #42bfd3 0 70%, #7656c9 0 100%)`;
  return <>
    <div className="overview-tabs"><button className={tab==='general'?'active':''} onClick={()=>setTab('general')}>General</button><button className={tab==='live'?'active':''} onClick={()=>setTab('live')}>Live activity</button><button className={tab==='insights'?'active':''} onClick={()=>setTab('insights')}>Model insights</button><button className="run-demo" onClick={()=>setSimulation(true)}><Play/> Run simulation</button></div>
    {tab==='live'&&<LiveActivity events={liveEvents} connection={connection} onSelect={event=>{setSelected(event);setTab('insights')}}/>}
    {tab==='insights'&&<ModelInsights event={selected||liveEvents[0]||null}/>}
    {tab==='general'&&<>
      <section className="behavior-hero"><div className="hero-copy"><span>LIVE BEHAVIOR POSTURE</span><div className="posture-line"><h2>{riskLoad>=70?'Critical behavior pressure':riskLoad>=50?'Elevated behavior pressure':'Behavior remains stable'}</h2><b className={riskLoad>=70?'critical':riskLoad>=50?'elevated':'stable'}>{riskLoad}/100</b></div><p>Deviance is correlating identity, device, location, travel, access, and volume signals across the active organization window.</p><div className="hero-metrics"><div><strong>{metrics.events_analyzed}</strong><span>events analyzed</span></div><div><strong>{metrics.unresolved_alerts}</strong><span>unresolved alerts</span></div><div><strong>{metrics.critical_alerts}</strong><span>critical priority</span></div><div title="Analyst dispositions marked false positive divided by reviewed alerts in the last 24 hours."><strong>{fp}%</strong><span>analyst-marked false positives · last 24h</span></div></div></div><div className="signal-pulse"><div className="pulse-head"><span>MODEL PULSE</span><b>LIVE</b></div><div className="pulse-bars">{recentRisk.map((item,index)=><i key={index} style={{height:`${Math.max(12,item.risk)}%`}} className={item.risk>=70?'hot':item.risk>=50?'warm':''}/>)}</div><div className="pulse-scale"><span>−20 events</span><span>now</span></div></div></section>
      <section className="system-strip"><Info label="Detection ensemble" value="Isolation Forest + GRU + calibrated RF"/><Info label="Behavior window" value="1 min–30 day + 10-event sequence"/><Info label="Feature contract" value={`${model?.feature_names?.length||24} signals · schema ${model?.feature_schema_version||'2.0.0'}`}/><Info label="Decision boundary" value={model?.alert_threshold?`${model.alert_threshold.toFixed(1)} risk score`:'budget calibrated'}/><Info label="Analyst budget" value={`${metrics.top_1_percent_precision.toFixed(0)}% precision · top 1%`}/><Info label="Inference latency" value={`${metrics.average_inference_latency_ms} ms`} accent/></section>
      <section className="overview-cards"><article className="clean-card status-card"><div className="section-heading"><h2>Detections by status</h2><button>Shared metrics <ChevronDown/></button></div><div className="status-content"><div className="donut" style={{background:riskMix}}><div><span>Total</span><strong>{metrics.total_alerts}</strong></div></div><div className="status-metrics"><CircleMetric value={metrics.open_alerts} label="Open" color="#d8387e" total={metrics.total_alerts}/><CircleMetric value={metrics.investigating_alerts} label="Investigating" color="#f6bd19" total={metrics.total_alerts}/><CircleMetric value={metrics.reviewed_alerts} label="Reviewed" color="#42bfd3" total={metrics.total_alerts}/><CircleMetric value={metrics.critical_alerts} label="Critical" color="#7656c9" total={metrics.total_alerts}/></div></div></article>
        <article className="clean-card owner-card"><div className="section-heading"><h2>Detections by attack class</h2><span>Alert verdicts</span></div><div className="attack-bars">{Object.entries(metrics.attacks_by_type).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,count],index)=><div key={name}><span className="class-avatar" style={{background:palette[index]}}>{name.slice(0,2).toUpperCase()}</span><div><label>{name.replaceAll('_',' ')}</label><span><i style={{width:`${Math.max(6,count/maxAttack*100)}%`,background:palette[index]}}/></span></div><strong>{count}</strong></div>)}</div></article></section>
      <section className="clean-card timeline-card"><div className="section-heading"><h2>Risk timeline</h2><div className="timeline-legend"><span><i className="normal"/>Normal range</span><span><i className="elevated"/>Elevated risk</span></div></div><ResponsiveContainer width="100%" height={190}><AreaChart data={metrics.risk_trend}><defs><linearGradient id="cleanRisk" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7656c9" stopOpacity={.2}/><stop offset="100%" stopColor="#7656c9" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--grid)" strokeDasharray="4 4" vertical={false}/><XAxis dataKey="id" tick={{fill:'var(--muted)',fontSize:12}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tick={{fill:'var(--muted)',fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:10,color:'var(--text)',fontSize:13}}/><Area type="monotone" dataKey="risk" stroke="#7656c9" fill="url(#cleanRisk)" strokeWidth={2}/></AreaChart></ResponsiveContainer></section>
    </>}
    {simulation&&<SimulationModal onClose={()=>setSimulation(false)}/>}
  </>;
}
function Info({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className="info-field"><span>{label}</span><strong>{value}</strong>{accent&&<div className="latency-track"><i/></div>}</div>}
function CircleMetric({value,label,color,total}:{value:number;label:string;color:string;total:number}){const percent=Math.max(8,value/Math.max(total,1)*100);return <div className="circle-metric"><div style={{background:`conic-gradient(${color} ${percent}%, var(--soft-fill) 0)`}}><span>{value}</span></div><label>{label}</label></div>}
